name: Free AI YouTube Bot

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install Python packages
        run: |
          pip install edge-tts

      - name: Run bot
        run: |
          python main.py